name: Test 10610

on:
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14']

    steps:
      - name : Get details
        run : |
          cd /Applications/
          ls -ltr
