name: Testing Generic

on:
  workflow_dispatch:
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-12', 'macos-13', 'macos-14-large']
        
    runs-on: ${{ matrix.os }}

    steps: 
    - name: Run
      shell: bash
      run: |
        cd /Applications/
        ls -ltr

    - name: Install Parallels
      shell: bash
      run: |
        brew install --cask parallels
        brew install --cask parallels-virtualization-sdk

    - name: Validate Kernel extension
      run: |
        MAX_RETRIES=2
        RETRY_COUNT=0
        until [ $RETRY_COUNT -ge $MAX_RETRIES ]
        do
          sudo kextload /Applications/Parallels\ Desktop.app/Contents/Library/Extensions/10.9/prl_hypervisor.kext && break
          RETRY_COUNT=$((RETRY_COUNT+1))
          echo "Waiting before retrying..."
          sleep 5
        done
