name: Testing Generic

on:
  workflow_dispatch:
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-12', 'macos-13', 'macos-14']
        
    runs-on: ${{ matrix.os }}

    steps: 
    - name: Run
      shell: bash
      run: |
        cd /Applications/
        ls -ltr
